/***************************************************************************
* 32ビット色コード for PSP  DXライブラリPortable v0.5.7                    *
***************************************************************************/

//    基本のシンプル20色
#define    BLACK           0xFF000000        //  黒色　　　■■■■■■■■
#define    BLUE            0xFFFF0000        //  青色　　　■■■■■■■■
#define    RED             0xFF0000FF        //  赤色　　　■■■■■■■■
#define    GREEN           0xFF00FF00        //  緑色　　　■■■■■■■■
#define    DARKBLUE        0xFF800000        //  紺色　　　■■■■■■■■
#define    LIGHTBLUE       0xFFFA0000        //  水色　　　■■■■■■■■
#define    BROWN           0xFF404080        //  茶色　　　■■■■■■■■
#define    PINK            0xFFFF80FF        //  桃色　　　■■■■■■■■
#define    DARKGREEN       0xFF008000        //  深緑色　　■■■■■■■■
#define    YELLOGREEN      0xFF00FF80        //  黄緑色　　■■■■■■■■
#define    PURPLE          0xFFFF0080        //  紫色　　　■■■■■■■■
#define    ORANGE          0xFF4080FF        //  橙色　　　■■■■■■■■
#define    LEMON           0xFF80FFFF        //  レモン色　■■■■■■■■
#define    YELLOW          0xFF00FFFF        //  黄色　　　■■■■■■■■
#define    SKYBLUE         0xFFFFFF00        //  空色　　　■■■■■■■■
#define    PEARLORANGE     0xFF75BAFF        //  肌色　　　■■■■■■■■
#define    GRAY            0xFF808080        //  灰色　　　■■■■■■■■
#define    SILVER          0xFFC0C0C0        //  銀色　　　■■■■■■■■
#define    GOLD            0xFF20C0E6        //  金色　　　■■■■■■■■
#define    WHITE           0xFFFFFFFF        //  白色　　　□□□□□□□□

//    基本の20色
#define    XVI_COLOR_BLACK        0xFF000000  //  黒色　　　■■■■■■■■
#define    XVI_COLOR_BLUE         0xFFFF0000  //  青色　　　■■■■■■■■
#define    XVI_COLOR_RED          0xFF0000FF  //  赤色　　　■■■■■■■■
#define    XVI_COLOR_GREEN        0xFF00FF00  //  緑色　　　■■■■■■■■
#define    XVI_COLOR_DARKBLUE     0xFF800000  //  紺色　　　■■■■■■■■
#define    XVI_COLOR_MARINBLUE    0xFFFA0000  //  水色　　　■■■■■■■■
#define    XVI_COLOR_BROWN        0xFF404080  //  茶色　　　■■■■■■■■
#define    XVI_COLOR_PINK         0xFFFF80FF  //  桃色　　　■■■■■■■■
#define    XVI_COLOR_DARKGREEN    0xFF008000  //  深緑色　　■■■■■■■■
#define    XVI_COLOR_YELLOGREEN   0xFF00FF80  //  黄緑色　　■■■■■■■■
#define    XVI_COLOR_PURPLE       0xFFFF0080  //  紫色　　　■■■■■■■■
#define    XVI_COLOR_ORANGE       0xFF4080FF  //  橙色　　　■■■■■■■■
#define    XVI_COLOR_LEMON        0xFF80FFFF  //  レモン色　■■■■■■■■
#define    XVI_COLOR_YELLOW       0xFF00FFFF  //  黄色　　　■■■■■■■■
#define    XVI_COLOR_SKYBLUE      0xFFFFFF00  //  空色　　　■■■■■■■■
#define    XVI_COLOR_PEARLORANGE  0xFF75BAFF  //  肌色　　　■■■■■■■■
#define    XVI_COLOR_GRAY         0xFF808080  //  灰色　　　■■■■■■■■
#define    XVI_COLOR_SILVER       0xFFC0C0C0  //  銀色　　　■■■■■■■■
#define    XVI_COLOR_GOLD         0xFF20C0E6  //  金色　　　■■■■■■■■
#define    XVI_COLOR_WHITE        0xFFFFFFFF  //  白色　　　□□□□□□□□

//    ホームページデザインでよく利用されている色（アルファベット順）
#define    HTML_COLOR_AliceBlue            0xFFFFF8F0  //■■■■■■■■
#define    HTML_COLOR_AntiqueWhite         0xFFD7EBFA  //■■■■■■■■
#define    HTML_COLOR_Aqua                 0xFFFFFF00  //■■■■■■■■
#define    HTML_COLOR_Aquamarine           0xFFD4FF7F  //■■■■■■■■
#define    HTML_COLOR_Azure                0xFFFFFFF0  //■■■■■■■■
#define    HTML_COLOR_Beige                0xFFDCF5F5  //■■■■■■■■
#define    HTML_COLOR_Bisque               0xFFC4E4FF  //■■■■■■■■
#define    HTML_COLOR_Black                0xFF000000  //■■■■■■■■
#define    HTML_COLOR_BlanchedAlmond       0xFFCDEBFF  //■■■■■■■■
#define    HTML_COLOR_Blue                 0xFFFF0000  //■■■■■■■■
#define    HTML_COLOR_BlueViolet           0xFFE22B8A  //■■■■■■■■
#define    HTML_COLOR_Brown                0xFF2A2AA5  //■■■■■■■■
#define    HTML_COLOR_BurlyWood            0xFF87B8DE  //■■■■■■■■
#define    HTML_COLOR_CadetBlue            0xFFA09E5F  //■■■■■■■■
#define    HTML_COLOR_Chartreuse           0xFF00FF7F  //■■■■■■■■
#define    HTML_COLOR_Chocolate            0xFF1E69D2  //■■■■■■■■
#define    HTML_COLOR_Coral                0xFF507FFF  //■■■■■■■■
#define    HTML_COLOR_CornflowerBlue       0xFFED9564  //■■■■■■■■
#define    HTML_COLOR_Cornsilk             0xFFDCF8FF  //■■■■■■■■
#define    HTML_COLOR_Crimson              0xFF3C14DC  //■■■■■■■■
#define    HTML_COLOR_Cyan                 0xFFFFFF00  //■■■■■■■■
#define    HTML_COLOR_DarkBlue             0xFF8B0000  //■■■■■■■■
#define    HTML_COLOR_DarkCyan             0xFF8B8B00  //■■■■■■■■
#define    HTML_COLOR_DarkGoldenrod        0xFF0B86B8  //■■■■■■■■
#define    HTML_COLOR_DarkGray             0xFFA9A9A9  //■■■■■■■■
#define    HTML_COLOR_DarkGreen            0xFF006400  //■■■■■■■■
#define    HTML_COLOR_DarkKhaki            0xFF6BB7BD  //■■■■■■■■
#define    HTML_COLOR_DarkMagenta          0xFF8B008B  //■■■■■■■■
#define    HTML_COLOR_DarkOliveGreen       0xFF2F6B55  //■■■■■■■■
#define    HTML_COLOR_DarkOrange           0xFF008CFF  //■■■■■■■■
#define    HTML_COLOR_DarkOrchid           0xFFCC3299  //■■■■■■■■
#define    HTML_COLOR_DarkRed              0xFF00008B  //■■■■■■■■
#define    HTML_COLOR_DarkSalmon           0xFF7A96E9  //■■■■■■■■
#define    HTML_COLOR_DarkSeaGreen         0xFF8BBC8F  //■■■■■■■■
#define    HTML_COLOR_DarkSlateBlue        0xFF8B3D48  //■■■■■■■■
#define    HTML_COLOR_DarkSlateGray        0xFF4F4F2F  //■■■■■■■■
#define    HTML_COLOR_DarkTurquoise        0xFFD1CE00  //■■■■■■■■
#define    HTML_COLOR_DarkViolet           0xFFD30094  //■■■■■■■■
#define    HTML_COLOR_DeepPink             0xFF9314FF  //■■■■■■■■
#define    HTML_COLOR_DeepSkyBlue          0xFFFFBF00  //■■■■■■■■
#define    HTML_COLOR_DimGray              0xFF696969  //■■■■■■■■
#define    HTML_COLOR_DodgerBlue           0xFFFF901E  //■■■■■■■■
#define    HTML_COLOR_Firebrick            0xFF2222B2  //■■■■■■■■
#define    HTML_COLOR_FloralWhite          0xFFF0FAFF  //■■■■■■■■
#define    HTML_COLOR_ForestGreen          0xFF228B22  //■■■■■■■■
#define    HTML_COLOR_Fuchsia              0xFFFF00FF  //■■■■■■■■
#define    HTML_COLOR_Gainsboro            0xFFDCDCDC  //■■■■■■■■
#define    HTML_COLOR_GhostWhite           0xFFFFF8F8  //■■■■■■■■
#define    HTML_COLOR_Gold                 0xFF00D7FF  //■■■■■■■■
#define    HTML_COLOR_Goldenrod            0xFF20A5DA  //■■■■■■■■
#define    HTML_COLOR_Gray                 0xFF808080  //■■■■■■■■
#define    HTML_COLOR_Green                0xFF008000  //■■■■■■■■
#define    HTML_COLOR_GreenYellow          0xFF2FFFAD  //■■■■■■■■
#define    HTML_COLOR_Honeydew             0xFFF0FFF0  //■■■■■■■■
#define    HTML_COLOR_HotPink              0xFFB469FF  //■■■■■■■■
#define    HTML_COLOR_IndianRed            0xFF5C5CCD  //■■■■■■■■
#define    HTML_COLOR_Indigo               0xFF82004B  //■■■■■■■■
#define    HTML_COLOR_Ivory                0xFFF0FFFF  //■■■■■■■■
#define    HTML_COLOR_Khaki                0xFF8CE6F0  //■■■■■■■■
#define    HTML_COLOR_Lavender             0xFFFAE6E6  //■■■■■■■■
#define    HTML_COLOR_LavenderBlush        0xFFF5F0FF  //■■■■■■■■
#define    HTML_COLOR_LawnGreen            0xFF00FC7C  //■■■■■■■■
#define    HTML_COLOR_LemonChiffon         0xFFCDFAFF  //■■■■■■■■
#define    HTML_COLOR_LightBlue            0xFFE6D8AD  //■■■■■■■■
#define    HTML_COLOR_LightCoral           0xFF8080F0  //■■■■■■■■
#define    HTML_COLOR_LightCyan            0xFFFFFFE0  //■■■■■■■■
#define    HTML_COLOR_LightGoldenrodYellow 0xFFD2FAFA  //■■■■■■■■
#define    HTML_COLOR_LightGray            0xFFD3D3D3  //■■■■■■■■
#define    HTML_COLOR_LightGreen           0xFF90EE90  //■■■■■■■■
#define    HTML_COLOR_LightPink            0xFFC1B6FF  //■■■■■■■■
#define    HTML_COLOR_LightSalmon          0xFF7AA0FF  //■■■■■■■■
#define    HTML_COLOR_LightSeaGreen        0xFFAAB220  //■■■■■■■■
#define    HTML_COLOR_LightSkyBlue         0xFFFACE87  //■■■■■■■■
#define    HTML_COLOR_LightSlateGray       0xFF998877  //■■■■■■■■
#define    HTML_COLOR_LightSteelBlue       0xFFDEC4B0  //■■■■■■■■
#define    HTML_COLOR_LightYellow          0xFFE0FFFF  //■■■■■■■■
#define    HTML_COLOR_Lime                 0xFF00FF00  //■■■■■■■■
#define    HTML_COLOR_LimeGreen            0xFF32CD32  //■■■■■■■■
#define    HTML_COLOR_Linen                0xFFE6F0FA  //■■■■■■■■
#define    HTML_COLOR_Magenta              0xFFFF00FF  //■■■■■■■■
#define    HTML_COLOR_Maroon               0xFF000080  //■■■■■■■■
#define    HTML_COLOR_MediumAquamarine     0xFFAACD66  //■■■■■■■■
#define    HTML_COLOR_MediumBlue           0xFFCD0000  //■■■■■■■■
#define    HTML_COLOR_MediumOrchid         0xFFD355BA  //■■■■■■■■
#define    HTML_COLOR_MediumPurple         0xFFDB7093  //■■■■■■■■
#define    HTML_COLOR_MediumSeaGreen       0xFF71B33C  //■■■■■■■■
#define    HTML_COLOR_MediumSlateBlue      0xFFEE687B  //■■■■■■■■
#define    HTML_COLOR_MediumSpringGreen    0xFF9AFA00  //■■■■■■■■
#define    HTML_COLOR_MediumTurquoise      0xFFCCD148  //■■■■■■■■
#define    HTML_COLOR_MediumVioletRed      0xFF8515C7  //■■■■■■■■
#define    HTML_COLOR_MidnightBlue         0xFF701919  //■■■■■■■■
#define    HTML_COLOR_MintCream            0xFFFAFFF5  //■■■■■■■■
#define    HTML_COLOR_MistyRose            0xFFE1E4FF  //■■■■■■■■
#define    HTML_COLOR_Moccasin             0xFFB5E4FF  //■■■■■■■■
#define    HTML_COLOR_NavajoWhite          0xFFADDEFF  //■■■■■■■■
#define    HTML_COLOR_Navy                 0xFF800000  //■■■■■■■■
#define    HTML_COLOR_OldLace              0xFFE6F5FD  //■■■■■■■■
#define    HTML_COLOR_Olive                0xFF008080  //■■■■■■■■
#define    HTML_COLOR_OliveDrab            0xFF238E6B  //■■■■■■■■
#define    HTML_COLOR_Orange               0xFF00A5FF  //■■■■■■■■
#define    HTML_COLOR_OrangeRed            0xFF0045FF  //■■■■■■■■
#define    HTML_COLOR_Orchid               0xFFD670DA  //■■■■■■■■
#define    HTML_COLOR_PaleGoldenrod        0xFFAAE8EE  //■■■■■■■■
#define    HTML_COLOR_PaleGreen            0xFF98FB98  //■■■■■■■■
#define    HTML_COLOR_PaleTurquoise        0xFFEEEEAF  //■■■■■■■■
#define    HTML_COLOR_PaleVioletRed        0xFF9370DB  //■■■■■■■■
#define    HTML_COLOR_PapayaWhip           0xFFD5EFFF  //■■■■■■■■
#define    HTML_COLOR_PeachPuff            0xFFB9DAFF  //■■■■■■■■
#define    HTML_COLOR_Peru                 0xFF3F85CD  //■■■■■■■■
#define    HTML_COLOR_Pink                 0xFFCBC0FF  //■■■■■■■■
#define    HTML_COLOR_Plum                 0xFFDDA0DD  //■■■■■■■■
#define    HTML_COLOR_PowderBlue           0xFFE6E0B0  //■■■■■■■■
#define    HTML_COLOR_Purple               0xFF800080  //■■■■■■■■
#define    HTML_COLOR_Red                  0xFF0000FF  //■■■■■■■■
#define    HTML_COLOR_RosyBrown            0xFF8F8FBC  //■■■■■■■■
#define    HTML_COLOR_RoyalBlue            0xFFE16941  //■■■■■■■■
#define    HTML_COLOR_SaddleBrown          0xFF13458B  //■■■■■■■■
#define    HTML_COLOR_Salmon               0xFF7280FA  //■■■■■■■■
#define    HTML_COLOR_SandyBrown           0xFF60A4F4  //■■■■■■■■
#define    HTML_COLOR_SeaGreen             0xFF578B2E  //■■■■■■■■
#define    HTML_COLOR_SeaShell             0xFFEEF5FF  //■■■■■■■■
#define    HTML_COLOR_Sienna               0xFF2D52A0  //■■■■■■■■
#define    HTML_COLOR_Silver               0xFFC0C0C0  //■■■■■■■■
#define    HTML_COLOR_SkyBlue              0xFFEBCE87  //■■■■■■■■
#define    HTML_COLOR_SlateBlue            0xFFCD5A6A  //■■■■■■■■
#define    HTML_COLOR_SlateGray            0xFF908070  //■■■■■■■■
#define    HTML_COLOR_Snow                 0xFFFAFAFF  //■■■■■■■■
#define    HTML_COLOR_SpringGreen          0xFF7FFF00  //■■■■■■■■
#define    HTML_COLOR_SteelBlue            0xFFB48246  //■■■■■■■■
#define    HTML_COLOR_Tan                  0xFF8CB4D2  //■■■■■■■■
#define    HTML_COLOR_Teal                 0xFF808000  //■■■■■■■■
#define    HTML_COLOR_Thistle              0xFFD8BFD8  //■■■■■■■■
#define    HTML_COLOR_Tomato               0xFF4763FF  //■■■■■■■■
#define    HTML_COLOR_Transparent          0x00FFFFFF  //■■■■■■■■
#define    HTML_COLOR_Turquoise            0xFFD0E040  //■■■■■■■■
#define    HTML_COLOR_Violet               0xFFEE82EE  //■■■■■■■■
#define    HTML_COLOR_Wheat                0xFFB3DEF5  //■■■■■■■■
#define    HTML_COLOR_White                0xFFFFFFFF  //■■■■■■■■
#define    HTML_COLOR_WhiteSmoke           0xFFF5F5F5  //■■■■■■■■
#define    HTML_COLOR_Yellow               0xFF00FFFF  //■■■■■■■■
#define    HTML_COLOR_YellowGreen          0xFF32CD9A  //■■■■■■■■

//    32ビットカラーの16進数コードを ＲＧＢから作成する計算式
#define  RGB(r,g,b) ((((long)b<<16)|((long)g<<8)|((long)r))|0xFF000000)

//    パーセント単位で指定する際の定義。
//    100パーセントが255になるように計算してます
#define    P100      255       //   100%    最大   MAX
#define    P90       229       //    90%
#define    P80       205       //    80%
#define    P75       191       //    75%    3/4    4分の3
#define    P70       179       //    70%
#define    P60       152       //    60%
#define    P50       127       //    50%    半分   2分の1
#define    P40       102       //    40%
#define    P30        77       //    30%
#define    P25        63       //    25%    1/4    4分の1
#define    P20        51       //    20%
#define    P10        25       //    10%
#define    P0          0       //     0%    無し   ZERO
